//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heimdall.Assets {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heimdall.Assets.SQLResources", typeof(SQLResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a update HUser set 
        ///Name = @name,
        ///Password = @password,
        ///OrganizationId = @organizationId,
        ///Email = @email,
        ///PhoneNumber = @phoneNumber,
        ///Address = @address
        ///where Id = @id.
        /// </summary>
        internal static string ChangeFatUserSQL {
            get {
                return ResourceManager.GetString("ChangeFatUserSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a update Organization set 
        ///Name = @name,
        ///Phone = @phone,
        ///Address = @address
        ///where Id = @id.
        /// </summary>
        internal static string ChangeOrganizationSQL {
            get {
                return ResourceManager.GetString("ChangeOrganizationSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a update User set 
        ///Name = @name,
        ///Password = @password,
        ///OrganizationId = @organizationId
        ///where Id = @id.
        /// </summary>
        internal static string ChangeThinUserSQL {
            get {
                return ResourceManager.GetString("ChangeThinUserSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select * from Organization where Id = @id.
        /// </summary>
        internal static string GetOrganizationByIdSQL {
            get {
                return ResourceManager.GetString("GetOrganizationByIdSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select * from HUser where Email = @email.
        /// </summary>
        internal static string GetUserByEmailSQL {
            get {
                return ResourceManager.GetString("GetUserByEmailSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select * from HUser where Name = @name.
        /// </summary>
        internal static string GetUserByNameSQL {
            get {
                return ResourceManager.GetString("GetUserByNameSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a insert into HUser (Id, Name, Password, OrganizationId, Email, PhoneNumber, Address)
        ///values (@id, @name, @password, @organizationId, @email, @phoneNumber, @address).
        /// </summary>
        internal static string RegisterFatUserSQL {
            get {
                return ResourceManager.GetString("RegisterFatUserSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a insert into Organization 
        ///(Id, Name, Phone, Address) 
        ///values 
        ///(@id, @name, @phone, @address).
        /// </summary>
        internal static string RegisterOrganizationSQL {
            get {
                return ResourceManager.GetString("RegisterOrganizationSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a insert into HUser (Id, Name, Password, OrganizationId)
        ///values (@id, @name, @password, @organizationId).
        /// </summary>
        internal static string RegisterThinUserSQL {
            get {
                return ResourceManager.GetString("RegisterThinUserSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a delete from Organization where Id = @id.
        /// </summary>
        internal static string RemoveOrganizationSQL {
            get {
                return ResourceManager.GetString("RemoveOrganizationSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a delete from HUser where Id = @id.
        /// </summary>
        internal static string RemoveUserSQL {
            get {
                return ResourceManager.GetString("RemoveUserSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select * from Organization where Name like @name.
        /// </summary>
        internal static string SearchOrganizationSQL {
            get {
                return ResourceManager.GetString("SearchOrganizationSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select * from HUser where Name like @name.
        /// </summary>
        internal static string SearchUsersSQL {
            get {
                return ResourceManager.GetString("SearchUsersSQL", resourceCulture);
            }
        }
    }
}
